### ISSUE TITLE
map.setMapStyleV2

### ISSUE THREAD

**Issue by woxinqidai** [YangJianFei/vue-baidu-map-3x#11]
map.setMapStyleV2 不支持

**Comment by YangJianFei** [comment]
这个是支持的！看看你是怎么用的

**Comment by woxinqidai** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/8944833/192484892-6681ba66-3735-43c9-90cd-55796aaa2891.png">
使用 styleV2 版本的话，只能在事件中获取map实例，不能使用标签直接设置

**Comment by YangJianFei** [comment]
api默认使用的是setMapStyle，gl使用的是setMapStyleV2。刚更新了一个版本api3.0和gl都使用了setMapStyleV2

**Comment by woxinqidai** [comment]
👍🏻

**Comment by woxinqidai** [comment]
styleId 方式没有支持

<img width="450" alt="image" src="https://user-images.githubusercontent.com/8944833/192694580-d3cd279d-b670-4231-a6a9-b0f65b39e0b6.png">

<img width="384" alt="image" src="https://user-images.githubusercontent.com/8944833/192694483-bd41533b-76b0-4bd8-818e-b6d5818db9a7.png">

**Comment by woxinqidai** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/8944833/192699791-0343ccc8-3e6a-4c43-90aa-edda5204d4fb.png">

这个延迟太高了，初始闪烁严重，是否能放到触发 ready 事件的时候直接设置 mapStyle

**Comment by YangJianFei** [comment]
测试代码忘删了

**Comment by YangJianFei** [comment]
![image](https://user-images.githubusercontent.com/16703333/192702414-86b141d8-7083-4e93-9047-a84d3823c727.png)
现在只保留这一个了，styleId也支持了

**Comment by woxinqidai** [comment]
👍🏻 感谢感谢
