### ISSUE TITLE
全局引用图不出来

### ISSUE THREAD

**Issue by 5563** [YangJianFei/vue-baidu-map-3x#13]
![image](https://user-images.githubusercontent.com/57325200/195055880-72fd0bb9-a160-4a02-9fdc-3baa0a5145e1.png)
显示这个
![image](https://user-images.githubusercontent.com/57325200/195055991-d6929279-5423-40f2-ae8a-8cb3cf36c620.png)
为什么 改成局部引用之后图就能出来

**Comment by YangJianFei** [comment]
需要注意use和组件的区别：
app.use()需要使用 import BaiduMap from ...
局部引用使用 import {BaiduMap} from ...

**Comment by YangJianFei** [comment]
app.use()表示安装一个组件库：里面会自动把组件库里面的组件都安装后面使用不需要导入。
局部引用表示：需要引入具体的某一个组件。

只是刚好例子这里这样写了：
import BaiduMap from '...'; // 其实这里可以任意写 import Wahaha from '...'。但是局部引用只能写成：import {BaiduMap} from '...'
app.use(BaiduMap);
