### ISSUE TITLE
类型提示问题

### ISSUE THREAD

**Issue by YiguiDing** [YangJianFei/vue-baidu-map-3x#47]
这个地方可不可以加上types
![image](https://github.com/YangJianFei/vue-baidu-map-3x/assets/50746494/7b5acf16-9cee-4a35-bc5f-9211871441c9)

这样就不报错了：

![image](https://github.com/YangJianFei/vue-baidu-map-3x/assets/50746494/a6f7fb04-16e3-4cc2-a63b-6a0f9a8d9a8b)

否则会这样：
![image](https://github.com/YangJianFei/vue-baidu-map-3x/assets/50746494/0399256a-1923-4e37-bd04-434dc2736ec5)

**Comment by pangjianxin** [comment]
一样的问题
