### ISSUE TITLE
无法找到模块“vue-baidu-map-3x”的声明文件

### ISSUE THREAD

**Issue by Diaosi1111** [YangJianFei/vue-baidu-map-3x#7]
![image](https://user-images.githubusercontent.com/35657483/189524604-fbff938c-ec04-4273-9297-20a99796dd52.png)

**Comment by YangJianFei** [comment]
声明文件忘写在package.json里面了。已加，感谢分享！

**Comment by Diaosi1111** [comment]
还有就是文档右上角的github链接是不对的
