### ISSUE TITLE
bm-info-window 默认有异常阴影

### ISSUE THREAD

**Issue by Diaosi1111** [YangJianFei/vue-baidu-map-3x#8]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/35657483/189791760-bd0efbc6-1d58-456f-a5a8-6b22d2779ba6.png">

**Comment by YangJianFei** [comment]
![image](https://user-images.githubusercontent.com/16703333/190118916-77b1616c-9aac-4f93-ab97-ff5b5366281e.png)
![image](https://user-images.githubusercontent.com/16703333/190119154-4d64f3f8-6889-45f6-904e-273aba2537bc.png)

你那边是不是样式被覆盖了，文档和我本地都是正常的

**Comment by Diaosi1111** [comment]
可能我是webGL？

**Comment by Diaosi1111** [comment]
还有bm-maker的label选项无法使用

**Comment by Diaosi1111** [comment]
按需加载是不是还没实现锕

**Comment by Diaosi1111** [comment]
```vue
            <Marker v-for="point of pointMap.values()" :point="point" />

```
更新pointMap的时候marker会自动添加，但是bm-info-window不会添加

**Comment by YangJianFei** [comment]
> 可能我是webGL？

![image](https://user-images.githubusercontent.com/16703333/191194322-f5a9c4ec-1354-4550-8408-ce93bd3694d8.png)
gl也显示正常，应该就是你那边样式覆盖了

**Comment by YangJianFei** [comment]
> 还有bm-maker的label选项无法使用
> 
> ```
> vue-baidu-map-3x.es.js:158 
>         
>        Uncaught TypeError: Cannot read properties of undefined (reading 'offset')
>     at createLabel (vue-baidu-map-3x.es.js:158:18)
>     at Proxy.load (vue-baidu-map-3x.es.js:1217:44)
>     at Proxy.ready (vue-baidu-map-3x.es.js:654:14)
>     at E$1.emit (vue-baidu-map-3x.es.js:235:20)
>     at Object.$emit (vue-baidu-map-3x.es.js:261:32)
>     at g0.<anonymous> (vue-baidu-map-3x.es.js:510:19)
>     at ev.BaseClass.fire.ev.BaseClass.dispatchEvent (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:2632)
>     at getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:20:273002
> ```
> 
> ```
> <template>
>     <bm-marker :position="{lng: point.lng, lat: point.lat}" :dragging="false" :lable="point.id" @click="show=true">
>         <bm-info-window :show="show" @close="show=false" @open="show=true">ID:{{point.id}}</bm-info-window>
>     </bm-marker>
> </template>
> 
> <script setup lang="ts">
> import { Point } from './point';
> import { BmMarker, BmInfoWindow } from "vue-baidu-map-3x";
> const show = ref(false)
> defineProps<{ point: Point }>()
> </script>
> ```

![image](https://user-images.githubusercontent.com/16703333/191196793-e971c7d5-b3ab-4b40-ad14-7e5c1056956b.png)

![image](https://user-images.githubusercontent.com/16703333/191196586-60a63a0e-23b2-4383-9772-30973db8de07.png)
maker的label属性是一个Lable对象。效果如下
![image](https://user-images.githubusercontent.com/16703333/191197261-6b4de0e6-1ef6-455f-8631-5064935b0d71.png)

**Comment by YangJianFei** [comment]
> 按需加载是不是还没实现锕

按需加载还在开发中

**Comment by YangJianFei** [comment]
> ```
>             <Marker v-for="point of pointMap.values()" :point="point" />
> ```
> 
> 更新pointMap的时候marker会自动添加，但是bm-info-window不会添加

![image](https://user-images.githubusercontent.com/16703333/191201152-3356fffd-8041-4a60-bc52-7be2af39928a.png)
信息窗口不能循环添加只能添加一个
